# Generated by Django 4.1.7 on 2023-03-18 02:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rentsplit', '0003_alter_expense_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=64)),
                ('body', models.CharField(max_length=150)),
                ('created_date', models.DateField(default='03-17-2023')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_message', to='rentsplit.profileauth')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=150)),
                ('created_time', models.DateField(default='03-17-2023')),
                ('parent_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_reply', to='messageboard.messsage')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_reply', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='messsage',
            name='replies',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_message', to='messageboard.reply'),
        ),
        migrations.AddField(
            model_name='messsage',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_message', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messsage',
            name='users_read',
            field=models.ManyToManyField(related_name='read_message', to=settings.AUTH_USER_MODEL),
        ),
    ]
