# Generated by Django 4.1.7 on 2023-03-18 03:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messageboard', '0003_alter_message_users_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='users_read',
            field=models.ManyToManyField(blank=True, null=True, related_name='read_message', to=settings.AUTH_USER_MODEL),
        ),
    ]
