# Generated by Django 4.1.7 on 2023-03-18 23:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messageboard', '0008_alter_message_created_date_alter_reply_created_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='replies',
        ),
        migrations.AlterField(
            model_name='message',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2023, 3, 18, 23, 5, 30, 896955, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='reply',
            name='created_time',
            field=models.DateField(default=datetime.datetime(2023, 3, 18, 23, 5, 30, 896955, tzinfo=datetime.timezone.utc)),
        ),
    ]
