# Generated by Django 4.1.7 on 2023-03-02 06:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rentsplit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileauth',
            name='users',
        ),
        migrations.AddField(
            model_name='profileauth',
            name='users',
            field=models.ManyToManyField(related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
