# Generated by Django 4.1.7 on 2023-03-12 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rentsplit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileauth',
            name='description',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='profileauth',
            name='rent',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profileauth',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.RemoveField(
            model_name='profileauth',
            name='users',
        ),
        migrations.AddField(
            model_name='profileauth',
            name='users',
            field=models.ManyToManyField(related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('amount', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_fr_profile', to='rentsplit.profileauth')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_fr_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('name', 'profile')},
            },
        ),
    ]
