# Generated by Django 4.1.7 on 2023-03-03 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentsplit', '0003_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
