# Generated by Django 4.1.7 on 2023-03-03 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentsplit', '0005_expense_profile_alter_expense_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileauth',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
