# Generated by Django 4.1.7 on 2023-03-04 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentsplit', '0006_alter_profileauth_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileauth',
            name='rent',
            field=models.IntegerField(default=0),
        ),
    ]
