# Generated by Django 4.1.7 on 2023-03-09 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentsplit', '0007_profileauth_rent'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='expense',
            unique_together={('name', 'profile')},
        ),
    ]
