# Generated by Django 4.1.7 on 2023-03-09 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentsplit', '0009_profileuser_alter_profileauth_users'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='profileuser',
            unique_together={('profile',)},
        ),
    ]
