# Generated by Django 4.1.7 on 2023-03-09 05:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rentsplit', '0010_alter_profileuser_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileauth',
            name='users',
            field=models.ManyToManyField(related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ProfileUser',
        ),
    ]
