# Generated by Django 4.1.7 on 2023-03-09 06:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rentsplit', '0012_remove_profileauth_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='user',
        ),
        migrations.AddField(
            model_name='profileauth',
            name='users',
            field=models.ManyToManyField(related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
